---
# Set up Docker
# See also: legacy gce.sh script

- include_role:
    name: docker-prerequisites

# Distribution-specific tasks:
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include_role:
    name: docker-configuration
