---
# Set up Weave Kube on top of Kubernetes.
# Dependencies on other roles:
# - kubernetes

- name: configure weave net's cni plugin
  command: kubectl apply -f https://git.io/weave-kube

- name: list kubernetes' pods
  command: kubectl get pods --all-namespaces
  changed_when: false
  register: kubectl_get_pods
  tags:
    - output

- name: print outpout of `kubectl get pods --all-namespaces`
  debug: msg="{{ kubectl_get_pods.stdout_lines }}"
  tags:
    - output
